# Настройки стиля кода и форматирования

column_width = 120       # Ширина столбцов (в символах)
line_endings = "Unix"    # Тип окончаний строк (Unix стиль)
indent_type = "Spaces"   # Тип отступов (пробелы)
indent_width = 2         # Ширина отступа (в пробелах)
quote_style = "AutoPreferDouble"  # Стиль кавычек (автоматический, предпочтительно двойные)
call_parentheses = "None"  # Стиль скобок при вызове функций (без скобок)

